In [1]:
import pandas as pd

df = pd.read_csv('data/merged_zip_data.csv')
df.head()

,Zipcode,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population
0,10001,1012.0,829.0,879.0,North River,2720.0,72242.0
1,10002,3061.0,3337.0,2555.0,Newtown Creek,8953.0,188137.0
2,10003,924.0,865.0,7320.0,Newtown Creek,9109.0,188137.0
3,10004,147.0,176.0,119.0,Newtown Creek,442.0,188137.0
4,10005,235.0,198.0,81.0,Newtown Creek,514.0,188137.0

In [2]:
zipcodes_served = df.groupby('WRRF Name')['Zipcode'].unique().reset_index()
zipcodes_served

         WRRF Name                                            Zipcode
0        26th Ward                [11203, 11207, 11208, 11212, 11239]
1       Bowery Bay  [10044, 11101, 11102, 11103, 11104, 11105, 111...
2     Coney Island  [11210, 11224, 11226, 11229, 11230, 11234, 112...
3      Hunts Point  [10459, 10460, 10462, 10463, 10464, 10465, 104...
4      Jamaica Bay  [11411, 11412, 11413, 11414, 11416, 11417, 114...
5    Newtown Creek  [10002, 10003, 10004, 10005, 10006, 10007, 100...
6      North River  [10001, 10011, 10014, 10018, 10019, 10023, 100...
7    Oakwood Beach         [10305, 10306, 10307, 10308, 10309, 10312]
8        Owls Head  [11204, 11209, 11214, 11218, 11219, 11220, 112...
9    Port Richmond         [10301, 10302, 10303, 10304, 10310, 10314]
10        Red Hook                       [11201, 11215, 11217, 11231]
11        Rockaway                [11691, 11692, 11693, 11694, 11697]
12  Tallman Island  [11004, 11005, 11354, 11355, 11356, 11357, 113...
13    Wards Island  [10021, 10028, 10029, 10030, 10032, 10033, 100...

In [3]:
zipcodes_served['Zip Codes Served'] = zipcodes_served['Zipcode'].apply(lambda x: ', '.join(map(str, x)))
zipcodes_served = zipcodes_served.drop(columns=['Zipcode'])


merged_df = df.merge(zipcodes_served, on='WRRF Name', how='left')


merged_df.drop('Zipcode', axis=1, inplace=True)

merged_df.drop_duplicates(subset='WRRF Name').reset_index(drop=True)

,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population,Zip Codes Served
0,1012.0,829.0,879.0,North River,2720.0,72242.0,"10001, 10011, 10014, 10018, 10019, 10023, 1002..."
1,3061.0,3337.0,2555.0,Newtown Creek,8953.0,188137.0,"10002, 10003, 10004, 10005, 10006, 10007, 1000..."
2,1517.0,2024.0,1928.0,Wards Island,5469.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003..."
3,472.0,402.0,274.0,Bowery Bay,1148.0,122994.0,"10044, 11101, 11102, 11103, 11104, 11105, 1110..."
4,1881.0,2020.0,2442.0,Port Richmond,6343.0,46435.0,"10301, 10302, 10303, 10304, 10310, 10314"
5,2771.0,2439.0,2606.0,Oakwood Beach,7816.0,44374.0,"10305, 10306, 10307, 10308, 10309, 10312"
6,3588.0,3934.0,3987.0,Hunts Point,11509.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046..."
7,726.0,923.0,709.0,Tallman Island,2358.0,74748.0,"11004, 11005, 11354, 11355, 11356, 11357, 1135..."
8,3384.0,2828.0,2768.0,Red Hook,8980.0,33636.0,"11201, 11215, 11217, 11231"
9,4055.0,4418.0,4278.0,26th Ward,12751.0,72091.0,"11203, 11207, 11208, 11212, 11239"
10,6533.0,6766.0,5140.0,Owls Head,18439.0,135396.0,"11204, 11209, 11214, 11218, 11219, 11220, 1122..."
11,4456.0,4759.0,4378.0,Coney Island,13593.0,117865.0,"11210, 11224, 11226, 11229, 11230, 11234, 1123..."
12,725.0,1425.0,993.0,Jamaica Bay,3143.0,131881.0,"11411, 11412, 11413, 11414, 11416, 11417, 1141..."
13,6282.0,6359.0,4749.0,Rockaway,17390.0,29986.0,"11691, 11692, 11693, 11694, 11697"

In [4]:
# merged_df.to_csv('data/facility_zip_data.csv', index=False)

In [5]:
# pre_omi_df = pd.read_csv('data/pre_omi')

In [9]:
def split_and_clean(zipcodes):
    if isinstance(zipcodes, str):
        return [int(zipcode.strip()) for zipcode in zipcodes.split(',')]
    return []

merged_df['Zip_Codes_Served'] = merged_df['Zip Codes Served'].apply(split_and_clean)
zips_exploded_df = merged_df.explode('Zip_Codes_Served')
zips_exploded_df = zips_exploded_df.rename(columns={'Zip_Codes_Served': 'Individual Zip Code'})
zips_exploded_df.drop('Zip Codes Served', axis=1, inplace=True)
zips_exploded_df.head()

,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population,Individual Zip Code
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10001
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10011
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10014
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10018
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10019

In [10]:
zips_exploded_df.to_csv('data/exploded_zips.csv', index=False)

In [13]:
# I discovered an error when visualizing this as a map. I need to correct one zip code's facility, and add one other zip.

rows_to_update = merged_df[merged_df['Zip Codes Served'].str.contains('10463')].index

for idx in rows_to_update:
    merged_df.at[idx, 'WRRF Name'] = 'Wards Island'

In [23]:
for idx, row in merged_df.iterrows():
    if row['WRRF Name'] == 'Wards Island':
        zip_codes = row['Zip Codes Served'].split(', ')
        if '10461' not in zip_codes:
            zip_codes.append('10461')
        merged_df.at[idx, 'Zip Codes Served'] = ', '.join(zip_codes)

print(merged_df[merged_df['WRRF Name'] == 'Wards Island'])

        5-9   10-14   15-19     WRRF Name  Total Population  \
17   1517.0  2024.0  1928.0  Wards Island            5469.0
24   2327.0  1747.0  1083.0  Wards Island            5157.0
25   3922.0  3588.0  4762.0  Wards Island           12272.0
26   1593.0  1768.0  1006.0  Wards Island            4367.0
28   2103.0  1938.0  2679.0  Wards Island            6720.0
29   2604.0  2913.0  2415.0  Wards Island            7932.0
31   2132.0  1929.0  1890.0  Wards Island            5951.0
33    994.0  1065.0   473.0  Wards Island            2532.0
35   1667.0  1714.0  1768.0  Wards Island            5149.0
36   1667.0  1714.0  1768.0  Wards Island            5149.0
38   1270.0  1072.0   674.0  Wards Island            3016.0
40    872.0   616.0  1095.0  Wards Island            2583.0
41   1936.0  1928.0  2281.0  Wards Island            6145.0
56   3499.0  3227.0  3379.0  Wards Island           10105.0
57   6280.0  7099.0  6229.0  Wards Island           19608.0
58   6325.0  6011.0  5621.0  Wards Island           17957.0
59   3142.0  3452.0  2323.0  Wards Island            8917.0
60   3728.0  3524.0  3564.0  Wards Island           10816.0
61   6352.0  7408.0  6949.0  Wards Island           20709.0
62   6498.0  7157.0  5060.0  Wards Island           18715.0
63   6766.0  6246.0  7831.0  Wards Island           20843.0
64   3588.0  3934.0  3987.0  Wards Island           11509.0
65   4037.0  4581.0  4262.0  Wards Island           12880.0
66   4928.0  5306.0  4147.0  Wards Island           14381.0
67   4435.0  4238.0  4593.0  Wards Island           13266.0
68   4435.0  4238.0  4593.0  Wards Island           13266.0
69    400.0   127.0    87.0  Wards Island             614.0
70   2061.0  2989.0  3558.0  Wards Island            8608.0
71   3980.0  5479.0  5243.0  Wards Island           14702.0
72   7567.0  7573.0  6254.0  Wards Island           21394.0
73   7336.0  5392.0  5943.0  Wards Island           18671.0
74   3478.0  5115.0  5243.0  Wards Island           13836.0
75    560.0   478.0   650.0  Wards Island            1688.0
76    783.0  1225.0  2067.0  Wards Island            4075.0
77   4879.0  4833.0  4569.0  Wards Island           14281.0
78   3626.0  4003.0  3978.0  Wards Island           11607.0
79   1178.0   863.0   695.0  Wards Island            2736.0
80   2242.0  1682.0  1761.0  Wards Island            5685.0
142  1171.0  1273.0  1651.0  Wards Island            4095.0
144  1171.0  1273.0  1651.0  Wards Island            4095.0

     Total WRRF Population                                   Zip Codes Served  \
17                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
24                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
25                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
26                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
28                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
29                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
31                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
33                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
35                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
36                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
38                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
40                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
41                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
56                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
57                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
58                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
59                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
60                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
61                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
62                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
63                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
64                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
65                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
66                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
67                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
68                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
69                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
70                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
71                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
72                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
73                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
74                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
75                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
76                240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
77                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
78                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
79                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
80                151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...
142               240219.0  10021, 10028, 10029, 10030, 10032, 10033, 1003...
144               151282.0  10459, 10460, 10462, 10463, 10464, 10465, 1046...

                                      Zip_Codes_Served
17   [10021, 10028, 10029, 10030, 10032, 10033, 100...
24   [10021, 10028, 10029, 10030, 10032, 10033, 100...
25   [10021, 10028, 10029, 10030, 10032, 10033, 100...
26   [10021, 10028, 10029, 10030, 10032, 10033, 100...
28   [10021, 10028, 10029, 10030, 10032, 10033, 100...
29   [10021, 10028, 10029, 10030, 10032, 10033, 100...
31   [10021, 10028, 10029, 10030, 10032, 10033, 100...
33   [10021, 10028, 10029, 10030, 10032, 10033, 100...
35   [10021, 10028, 10029, 10030, 10032, 10033, 100...
36   [10021, 10028, 10029, 10030, 10032, 10033, 100...
38   [10021, 10028, 10029, 10030, 10032, 10033, 100...
40   [10021, 10028, 10029, 10030, 10032, 10033, 100...
41   [10021, 10028, 10029, 10030, 10032, 10033, 100...
56   [10021, 10028, 10029, 10030, 10032, 10033, 100...
57   [10021, 10028, 10029, 10030, 10032, 10033, 100...
58   [10021, 10028, 10029, 10030, 10032, 10033, 100...
59   [10021, 10028, 10029, 10030, 10032, 10033, 100...
60   [10021, 10028, 10029, 10030, 10032, 10033, 100...
61   [10021, 10028, 10029, 10030, 10032, 10033, 100...
62   [10021, 10028, 10029, 10030, 10032, 10033, 100...
63   [10021, 10028, 10029, 10030, 10032, 10033, 100...
64   [10459, 10460, 10462, 10463, 10464, 10465, 104...
65   [10459, 10460, 10462, 10463, 10464, 10465, 104...
66   [10459, 10460, 10462, 10463, 10464, 10465, 104...
67   [10021, 10028, 10029, 10030, 10032, 10033, 100...
68   [10459, 10460, 10462, 10463, 10464, 10465, 104...
69   [10459, 10460, 10462, 10463, 10464, 10465, 104...
70   [10459, 10460, 10462, 10463, 10464, 10465, 104...
71   [10459, 10460, 10462, 10463, 10464, 10465, 104...
72   [10459, 10460, 10462, 10463, 10464, 10465, 104...
73   [10021, 10028, 10029, 10030, 10032, 10033, 100...
74   [10459, 10460, 10462, 10463, 10464, 10465, 104...
75   [10459, 10460, 10462, 10463, 10464, 10465, 104...
76   [10021, 10028, 10029, 10030, 10032, 10033, 100...
77   [10459, 10460, 10462, 10463, 10464, 10465, 104...
78   [10459, 10460, 10462, 10463, 10464, 10465, 104...
79   [10459, 10460, 10462, 10463, 10464, 10465, 104...
80   [10459, 10460, 10462, 10463, 10464, 10465, 104...
142  [10021, 10028, 10029, 10030, 10032, 10033, 100...
144  [10459, 10460, 10462, 10463, 10464, 10465, 104...

In [24]:
merged_df[merged_df['Zip Codes Served'].str.contains('10463')]

,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population,Zip Codes Served,Zip_Codes_Served
17,1517.0,2024.0,1928.0,Wards Island,5469.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
24,2327.0,1747.0,1083.0,Wards Island,5157.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
25,3922.0,3588.0,4762.0,Wards Island,12272.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
26,1593.0,1768.0,1006.0,Wards Island,4367.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
28,2103.0,1938.0,2679.0,Wards Island,6720.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
29,2604.0,2913.0,2415.0,Wards Island,7932.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
31,2132.0,1929.0,1890.0,Wards Island,5951.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
33,994.0,1065.0,473.0,Wards Island,2532.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
35,1667.0,1714.0,1768.0,Wards Island,5149.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
36,1667.0,1714.0,1768.0,Wards Island,5149.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
38,1270.0,1072.0,674.0,Wards Island,3016.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
40,872.0,616.0,1095.0,Wards Island,2583.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
41,1936.0,1928.0,2281.0,Wards Island,6145.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
56,3499.0,3227.0,3379.0,Wards Island,10105.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
57,6280.0,7099.0,6229.0,Wards Island,19608.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
58,6325.0,6011.0,5621.0,Wards Island,17957.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
59,3142.0,3452.0,2323.0,Wards Island,8917.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
60,3728.0,3524.0,3564.0,Wards Island,10816.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
61,6352.0,7408.0,6949.0,Wards Island,20709.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
62,6498.0,7157.0,5060.0,Wards Island,18715.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
63,6766.0,6246.0,7831.0,Wards Island,20843.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
64,3588.0,3934.0,3987.0,Wards Island,11509.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
65,4037.0,4581.0,4262.0,Wards Island,12880.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
66,4928.0,5306.0,4147.0,Wards Island,14381.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
67,4435.0,4238.0,4593.0,Wards Island,13266.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
68,4435.0,4238.0,4593.0,Wards Island,13266.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
69,400.0,127.0,87.0,Wards Island,614.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
70,2061.0,2989.0,3558.0,Wards Island,8608.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
71,3980.0,5479.0,5243.0,Wards Island,14702.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
72,7567.0,7573.0,6254.0,Wards Island,21394.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
73,7336.0,5392.0,5943.0,Wards Island,18671.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
74,3478.0,5115.0,5243.0,Wards Island,13836.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
75,560.0,478.0,650.0,Wards Island,1688.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
76,783.0,1225.0,2067.0,Wards Island,4075.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
77,4879.0,4833.0,4569.0,Wards Island,14281.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
78,3626.0,4003.0,3978.0,Wards Island,11607.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
79,1178.0,863.0,695.0,Wards Island,2736.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
80,2242.0,1682.0,1761.0,Wards Island,5685.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
142,1171.0,1273.0,1651.0,Wards Island,4095.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
144,1171.0,1273.0,1651.0,Wards Island,4095.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."

In [25]:
merged_df[merged_df['Zip Codes Served'].str.contains('10461')]

,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population,Zip Codes Served,Zip_Codes_Served
17,1517.0,2024.0,1928.0,Wards Island,5469.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
24,2327.0,1747.0,1083.0,Wards Island,5157.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
25,3922.0,3588.0,4762.0,Wards Island,12272.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
26,1593.0,1768.0,1006.0,Wards Island,4367.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
28,2103.0,1938.0,2679.0,Wards Island,6720.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
29,2604.0,2913.0,2415.0,Wards Island,7932.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
31,2132.0,1929.0,1890.0,Wards Island,5951.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
33,994.0,1065.0,473.0,Wards Island,2532.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
35,1667.0,1714.0,1768.0,Wards Island,5149.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
36,1667.0,1714.0,1768.0,Wards Island,5149.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
38,1270.0,1072.0,674.0,Wards Island,3016.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
40,872.0,616.0,1095.0,Wards Island,2583.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
41,1936.0,1928.0,2281.0,Wards Island,6145.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
56,3499.0,3227.0,3379.0,Wards Island,10105.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
57,6280.0,7099.0,6229.0,Wards Island,19608.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
58,6325.0,6011.0,5621.0,Wards Island,17957.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
59,3142.0,3452.0,2323.0,Wards Island,8917.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
60,3728.0,3524.0,3564.0,Wards Island,10816.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
61,6352.0,7408.0,6949.0,Wards Island,20709.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
62,6498.0,7157.0,5060.0,Wards Island,18715.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
63,6766.0,6246.0,7831.0,Wards Island,20843.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
64,3588.0,3934.0,3987.0,Wards Island,11509.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
65,4037.0,4581.0,4262.0,Wards Island,12880.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
66,4928.0,5306.0,4147.0,Wards Island,14381.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
67,4435.0,4238.0,4593.0,Wards Island,13266.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
68,4435.0,4238.0,4593.0,Wards Island,13266.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
69,400.0,127.0,87.0,Wards Island,614.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
70,2061.0,2989.0,3558.0,Wards Island,8608.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
71,3980.0,5479.0,5243.0,Wards Island,14702.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
72,7567.0,7573.0,6254.0,Wards Island,21394.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
73,7336.0,5392.0,5943.0,Wards Island,18671.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
74,3478.0,5115.0,5243.0,Wards Island,13836.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
75,560.0,478.0,650.0,Wards Island,1688.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
76,783.0,1225.0,2067.0,Wards Island,4075.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
77,4879.0,4833.0,4569.0,Wards Island,14281.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
78,3626.0,4003.0,3978.0,Wards Island,11607.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
79,1178.0,863.0,695.0,Wards Island,2736.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
80,2242.0,1682.0,1761.0,Wards Island,5685.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."
142,1171.0,1273.0,1651.0,Wards Island,4095.0,240219.0,"10021, 10028, 10029, 10030, 10032, 10033, 1003...","[10021, 10028, 10029, 10030, 10032, 10033, 100..."
144,1171.0,1273.0,1651.0,Wards Island,4095.0,151282.0,"10459, 10460, 10462, 10463, 10464, 10465, 1046...","[10459, 10460, 10462, 10463, 10464, 10465, 104..."

In [26]:
merged_df['Zip_Codes_Served'] = merged_df['Zip Codes Served'].apply(split_and_clean)
zips_exploded_df = merged_df.explode('Zip_Codes_Served')
zips_exploded_df = zips_exploded_df.rename(columns={'Zip_Codes_Served': 'Individual Zip Code'})
zips_exploded_df.drop('Zip Codes Served', axis=1, inplace=True)
zips_exploded_df.head()

,5-9,10-14,15-19,WRRF Name,Total Population,Total WRRF Population,Individual Zip Code
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10001
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10011
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10014
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10018
0,1012.0,829.0,879.0,North River,2720.0,72242.0,10019

In [27]:
zips_exploded_df.to_csv('data/exploded_zips.csv', index=False)